## Pandas learnings and solvings and questions and concepts and answers

In [4]:
import pandas as pd

data = {
    "Name": ["Rohan", "Rahul", "Amit", "Sneha", "Priya"],
    "Age": [25, 28, 24, 27, 30],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Mumbai"],
    "Salary": [50000, 70000, 45000, 65000, 80000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age    City  Salary
0  Rohan   25    Pune   50000
1  Rahul   28  Mumbai   70000
2   Amit   24   Delhi   45000
3  Sneha   27    Pune   65000
4  Priya   30  Mumbai   80000

In [5]:
df["Salary"]

print(df)

    Name  Age    City  Salary
0  Rohan   25    Pune   50000
1  Rahul   28  Mumbai   70000
2   Amit   24   Delhi   45000
3  Sneha   27    Pune   65000
4  Priya   30  Mumbai   80000

In [6]:
df[["Name","City","Salary"]]

    Name    City  Salary
0  Rohan    Pune   50000
1  Rahul  Mumbai   70000
2   Amit   Delhi   45000
3  Sneha    Pune   65000
4  Priya  Mumbai   80000

## LOC

In [7]:
df.loc[1,["Name","Salary"]]

Name      Rahul
Salary    70000
Name: 1, dtype: object

In [8]:
df.loc[df["City"] == "Pune",["Name","City","Salary"]]

    Name  City  Salary
0  Rohan  Pune   50000
3  Sneha  Pune   65000

In [9]:
df.loc[df["Salary"] > 60000, ["Name","Age"]]

    Name  Age
1  Rahul   28
3  Sneha   27
4  Priya   30

In [10]:
df.loc[df["Salary"] > 60000 ,["Name", "Age"]]

    Name  Age
1  Rahul   28
3  Sneha   27
4  Priya   30

In [11]:
df.loc[2,["Name"]]

Name    Amit
Name: 2, dtype: object

In [12]:
print(df)

    Name  Age    City  Salary
0  Rohan   25    Pune   50000
1  Rahul   28  Mumbai   70000
2   Amit   24   Delhi   45000
3  Sneha   27    Pune   65000
4  Priya   30  Mumbai   80000

## ILOC

In [13]:
print(df.iloc[2,3])
print(df.iloc[1:4])

45000
    Name  Age    City  Salary
1  Rahul   28  Mumbai   70000
2   Amit   24   Delhi   45000
3  Sneha   27    Pune   65000

In [14]:
print(df.iloc[[1,3],[0,3]])

    Name  Salary
1  Rahul   70000
3  Sneha   65000

In [15]:
df.loc[df["City"] =="Pune",["Name","Salary"]]

    Name  Salary
0  Rohan   50000
3  Sneha   65000

In [16]:
df.loc[(df["City"] =="Pune") & (df["Salary"] > 60000) , ["Name", "Salary"]]

    Name  Salary
3  Sneha   65000

In [17]:
df.loc[(df["City"] == "Pune")  &  (df["Salary"] > 60000) ,["Name","Salary"]]

    Name  Salary
3  Sneha   65000

In [18]:
df.loc[(df["City"] == "Pune") | (df["City"] == "Mumbai"),["Name","Salary","Age","City"]]

    Name  Salary  Age    City
0  Rohan   50000   25    Pune
1  Rahul   70000   28  Mumbai
3  Sneha   65000   27    Pune
4  Priya   80000   30  Mumbai

In [19]:
df.loc[(df["Age"] > 25) & (df["Salary"] < 80000),["Name","City","Salary"]]

    Name    City  Salary
1  Rahul  Mumbai   70000
3  Sneha    Pune   65000

## SORT_VALUES THIS WILL GIVE VALUES ON SORTING TO LOWEST TO HIGHEST BY DEFAULTS.
## IF WE WANT TO HIGHEST TO LOWEST THEN USE ASCENDING FUNCTION

In [20]:
df.sort_values("Salary")

    Name  Age    City  Salary
2   Amit   24   Delhi   45000
0  Rohan   25    Pune   50000
3  Sneha   27    Pune   65000
1  Rahul   28  Mumbai   70000
4  Priya   30  Mumbai   80000

## VALUES FROM HIGH TO LOW USING ASCENDING

In [21]:
df.sort_values("Salary", ascending = False)

    Name  Age    City  Salary
4  Priya   30  Mumbai   80000
1  Rahul   28  Mumbai   70000
3  Sneha   27    Pune   65000
0  Rohan   25    Pune   50000
2   Amit   24   Delhi   45000

## HEAD() and TAIL()
## so this is giving us first values which is at top

In [22]:
df.sort_values("Salary", ascending = False).head(3)

    Name  Age    City  Salary
4  Priya   30  Mumbai   80000
1  Rahul   28  Mumbai   70000
3  Sneha   27    Pune   65000

In [23]:
df.sort_values("Salary", ascending = False).tail(3)

    Name  Age   City  Salary
3  Sneha   27   Pune   65000
0  Rohan   25   Pune   50000
2   Amit   24  Delhi   45000

## QUES ON LEARNINGS

In [24]:
print(df)

    Name  Age    City  Salary
0  Rohan   25    Pune   50000
1  Rahul   28  Mumbai   70000
2   Amit   24   Delhi   45000
3  Sneha   27    Pune   65000
4  Priya   30  Mumbai   80000

In [25]:
df.loc[df["City"] == "Pune"].sort_values("Salary", ascending = False).head(4)

    Name  Age  City  Salary
3  Sneha   27  Pune   65000
0  Rohan   25  Pune   50000

In [26]:
df.loc[df["City"] == "Pune",["Name","Salary"]].sort_values ("Salary", ascending = False).head(5)

    Name  Salary
3  Sneha   65000
0  Rohan   50000

In [27]:
df.sort_values("Salary", ascending = False)[["Name","Salary"]].head(3)

    Name  Salary
4  Priya   80000
1  Rahul   70000
3  Sneha   65000

In [28]:
print(df)

    Name  Age    City  Salary
0  Rohan   25    Pune   50000
1  Rahul   28  Mumbai   70000
2   Amit   24   Delhi   45000
3  Sneha   27    Pune   65000
4  Priya   30  Mumbai   80000

In [29]:
df[df["City"].isin(["Pune","Delhi"])]

    Name  Age   City  Salary
0  Rohan   25   Pune   50000
2   Amit   24  Delhi   45000
3  Sneha   27   Pune   65000

In [30]:
df[df["Age"].between(25,28)]

    Name  Age    City  Salary
0  Rohan   25    Pune   50000
1  Rahul   28  Mumbai   70000
3  Sneha   27    Pune   65000

In [31]:
df[df["Salary"].between(50000,70000)]

    Name  Age    City  Salary
0  Rohan   25    Pune   50000
1  Rahul   28  Mumbai   70000
3  Sneha   27    Pune   65000

In [32]:
df.query("Salary >= 65000 and City == 'Mumbai'")

    Name  Age    City  Salary
1  Rahul   28  Mumbai   70000
4  Priya   30  Mumbai   80000

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Salary  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [34]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   26.800000  62000.000000
std     2.387467  14404.860291
min    24.000000  45000.000000
25%    25.000000  50000.000000
50%    27.000000  65000.000000
75%    28.000000  70000.000000
max    30.000000  80000.000000

In [35]:
df.head()
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   26.800000  62000.000000
std     2.387467  14404.860291
min    24.000000  45000.000000
25%    25.000000  50000.000000
50%    27.000000  65000.000000
75%    28.000000  70000.000000
max    30.000000  80000.000000

## IMPORTING FILE FROM SOURCES AND LOOK AT DATA WHAT DOES IT PROVIDES

In [36]:
print(df)

    Name  Age    City  Salary
0  Rohan   25    Pune   50000
1  Rahul   28  Mumbai   70000
2   Amit   24   Delhi   45000
3  Sneha   27    Pune   65000
4  Priya   30  Mumbai   80000

In [37]:
df.head()      ## shows the first rows so you can see what the data looks like

    Name  Age    City  Salary
0  Rohan   25    Pune   50000
1  Rahul   28  Mumbai   70000
2   Amit   24   Delhi   45000
3  Sneha   27    Pune   65000
4  Priya   30  Mumbai   80000

In [38]:
df.shape     ## Tells you how many rows and columns you have.

(5, 4)

In [39]:
df.info()       ## gives the structure of the dataset: column names, data types, non-null counts, etc.ō

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Salary  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [40]:
df.describe()      ## gives a statistical summary of numeric columns.

             Age        Salary
count   5.000000      5.000000
mean   26.800000  62000.000000
std     2.387467  14404.860291
min    24.000000  45000.000000
25%    25.000000  50000.000000
50%    27.000000  65000.000000
75%    28.000000  70000.000000
max    30.000000  80000.000000

In [41]:
df.columns    ## tells you what information/variables are available.

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

In [42]:
## Find all employees whose salary is greater than ₹60,000, and show only their Name, City, and Salary.

In [43]:
df.loc[df["Salary"] > 60000,["Name", "City","Salary"]]

    Name    City  Salary
1  Rahul  Mumbai   70000
3  Sneha    Pune   65000
4  Priya  Mumbai   80000

In [44]:
df.loc[df["City"] =="Mumbai",["Name","Salary"]].sort_values("Salary", ascending = False).head(2)

    Name  Salary
4  Priya   80000
1  Rahul   70000

In [45]:
df.loc[(df["Age"] > 25) & (df["City"] == "Pune"),["Name","Salary","Age"]].sort_values("Salary", ascending = False).head()

    Name  Salary  Age
3  Sneha   65000   27

In [46]:
df.loc[(df["City"].isin(["Pune","Mumbai"])) & (df["Salary"] > 60000 ) ,["Name","City","Salary"]].sort_values("Salary", ascending = False).head()

    Name    City  Salary
4  Priya  Mumbai   80000
1  Rahul  Mumbai   70000
3  Sneha    Pune   65000

In [47]:
df.loc[(df["Age"].between(25,30)) & (df["City"].isin(["Pune","Mumbai"])),["Name","Age","Salary"]].sort_values("Salary", ascending = False)

    Name  Age  Salary
4  Priya   30   80000
1  Rahul   28   70000
3  Sneha   27   65000
0  Rohan   25   50000

In [48]:
df.loc[(df["Salary"].between(50000,80000)) & (df["City"].isin(["Pune","Mumbai"])),
["Name","City","Salary"]].sort_values("Salary", ascending = False).head(2)

    Name    City  Salary
4  Priya  Mumbai   80000
1  Rahul  Mumbai   70000

## Imported movies.csv dataset for learnings

In [49]:
import pandas as pd

In [50]:
df = pd.read_csv("movie.csv", sep=";", encoding="cp1252")

In [51]:
df.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0

In [52]:
df.shape

(4000, 15)

In [53]:
df.columns

Index(['name', 'rating', 'genre', 'year', 'released', 'score', 'votes',
       'director', 'writer', 'star', 'country', 'budget', 'gross', 'company',
       'runtime'],
      dtype='object')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      4000 non-null   object
 1   rating    3960 non-null   object
 2   genre     4000 non-null   object
 3   year      4000 non-null   int64
 4   released  4000 non-null   object
 5   score     4000 non-null   float64
 6   votes     4000 non-null   float64
 7   director  4000 non-null   object
 8   writer    3999 non-null   object
 9   star      3999 non-null   object
 10  country   4000 non-null   object
 11  budget    4000 non-null   int64
 12  gross     3831 non-null   float64
 13  company   3990 non-null   object
 14  runtime   4000 non-null   float64
dtypes: float64(4), int64(2), object(9)
memory usage: 468.9+ KB

In [55]:
df.describe()

,year,score,votes,budget,gross,runtime
count,4000.000000,4000.000000,4.000000e+03,4.000000e+03,3.831000e+03,4000.000000
mean,1991.191500,6.321950,5.449450e+04,1.542740e+07,4.172202e+07,105.711750
std,5.934529,0.977101,1.427738e+05,2.248639e+07,9.259504e+07,18.470556
min,1980.000000,2.200000,5.100000e+01,0.000000e+00,3.090000e+02,55.000000
25%,1986.000000,5.700000,4.300000e+03,0.000000e+00,2.835743e+06,94.000000
50%,1991.000000,6.400000,1.300000e+04,7.000000e+06,1.183822e+07,102.000000
75%,1996.000000,7.000000,4.500000e+04,2.100000e+07,3.560495e+07,114.000000
max,2001.000000,9.300000,2.400000e+06,2.000000e+08,2.201647e+09,357.000000

In [56]:
df[["name","score","genre"]].head(15)

                                              name  score      genre
0                                      The Shining    8.4      Drama
1                                  The Blue Lagoon    5.8  Adventure
2   Star Wars: Episode V - The Empire Strikes Back    8.7     Action
3                                        Airplane!    7.7     Comedy
4                                       Caddyshack    7.3     Comedy
5                                  Friday the 13th    6.4     Horror
6                               The Blues Brothers    7.9     Action
7                                      Raging Bull    8.2  Biography
8                                      Superman II    6.8     Action
9                                  The Long Riders    7.0  Biography
10                           Any Which Way You Can    6.1     Action
11                          The Gods Must Be Crazy    7.3  Adventure
12                                          Popeye    5.3  Adventure
13                                 Ordinary People    7.7      Drama
14                                 Dressed to Kill    7.1      Crime

In [57]:
df[["name","score","genre"]].head()

                                             name  score      genre
0                                     The Shining    8.4      Drama
1                                 The Blue Lagoon    5.8  Adventure
2  Star Wars: Episode V - The Empire Strikes Back    8.7     Action
3                                       Airplane!    7.7     Comedy
4                                      Caddyshack    7.3     Comedy

In [58]:
df.isna().mean() *100

name        0.000
rating      1.000
genre       0.000
year        0.000
released    0.000
score       0.000
votes       0.000
director    0.000
writer      0.025
star        0.025
country     0.000
budget      0.000
gross       4.225
company     0.250
runtime     0.000
dtype: float64

In [59]:
df["gross"].dtype

dtype('float64')

In [60]:
df["gross"].median()

11838218.0

In [61]:
df["gross"] = df["gross"].fillna(df["gross"].median())

In [62]:
df["gross"].isna()

0       False
1       False
2       False
3       False
4       False
        ...
3995    False
3996    False
3997    False
3998    False
3999    False
Name: gross, Length: 4000, dtype: bool

In [63]:
df["rating"] = df["rating"].fillna(df["rating"].mode()[0])

In [64]:
df["rating"].isna().sum()

np.int64(0)

In [65]:
clean_df = df.dropna()

In [66]:
clean_df.shape

(3988, 15)

In [67]:
df.duplicated().sum()

np.int64(0)

In [68]:
df.dtypes

name         object
rating       object
genre        object
year          int64
released     object
score       float64
votes       float64
director     object
writer       object
star         object
country      object
budget        int64
gross       float64
company      object
runtime     float64
dtype: object

In [69]:
df["released"].head(10)

0        June 13, 1980 (United States)
1         July 2, 1980 (United States)
2        June 20, 1980 (United States)
3         July 2, 1980 (United States)
4        July 25, 1980 (United States)
5          May 9, 1980 (United States)
6        June 20, 1980 (United States)
7    December 19, 1980 (United States)
8        June 19, 1981 (United States)
9         May 16, 1980 (United States)
Name: released, dtype: object

In [70]:
df["released"].str.split("(")

0          [June 13, 1980 , United States)]
1           [July 2, 1980 , United States)]
2          [June 20, 1980 , United States)]
3           [July 2, 1980 , United States)]
4          [July 25, 1980 , United States)]
                       ...
3995    [February 1, 2002 , United States)]
3996         [September 12, 2001 , France)]
3997     [August 31, 2001 , United States)]
3998      [April 27, 2001 , United States)]
3999       [June 22, 2001 , United States)]
Name: released, Length: 4000, dtype: object

In [71]:
df["budget"] = df["budget"].astype(float)
df["budget"]

0       19000000.0
1        4500000.0
2       18000000.0
3        3500000.0
4        6000000.0
           ...
3995    13000000.0
3996           0.0
3997     5000000.0
3998    18000000.0
3999    70000000.0
Name: budget, Length: 4000, dtype: float64

In [72]:
df["year"] = df["year"].astype(str)
df["year"]

0       1980
1       1980
2       1980
3       1980
4       1980
        ...
3995    2001
3996    2001
3997    2001
3998    2001
3999    2001
Name: year, Length: 4000, dtype: object

In [73]:
df["score"] = df["score"].astype(int)
df["score"]

0       8
1       5
2       8
3       7
4       7
       ..
3995    6
3996    6
3997    6
3998    6
3999    4
Name: score, Length: 4000, dtype: int64

In [74]:
df["budget"] = df["budget"].astype(int)
df["year"] = df["year"].astype(int)
df["score"] = df["score"].astype(float)

In [75]:
df["country"] = df["country"].replace("U.S.A", "USA")
df["country"]

0       United Kingdom
1        United States
2        United States
3        United States
4        United States
             ...
3995    United Kingdom
3996            France
3997     United States
3998     United States
3999     United States
Name: country, Length: 4000, dtype: object

In [76]:
df = df.rename(columns={"company":"production_company"})

In [77]:
df["budget"] = df["budget"].astype(int)
df["budget"]

0       19000000
1        4500000
2       18000000
3        3500000
4        6000000
          ...
3995    13000000
3996           0
3997     5000000
3998    18000000
3999    70000000
Name: budget, Length: 4000, dtype: int64

In [78]:
df["year"] = df["year"].astype(str)
df["year"]

0       1980
1       1980
2       1980
3       1980
4       1980
        ...
3995    2001
3996    2001
3997    2001
3998    2001
3999    2001
Name: year, Length: 4000, dtype: object

In [79]:
df["budget_numeric"] = pd.to_numeric(df["budget"],errors = "coerce")
df["budget_numeric"]

0       19000000
1        4500000
2       18000000
3        3500000
4        6000000
          ...
3995    13000000
3996           0
3997     5000000
3998    18000000
3999    70000000
Name: budget_numeric, Length: 4000, dtype: int64

In [80]:
df["rating"] = df["rating"].replace("Not rated","unrated")
df["rating"]

0        R
1        R
2       PG
3       PG
4        R
        ..
3995     R
3996     R
3997     R
3998     R
3999    PG
Name: rating, Length: 4000, dtype: object

In [81]:
df = df.rename(columns = {"gross":"box_office"})

In [82]:
df = df.rename(columns = {"year":"year_numeric"})
df = df["year_numeric"].astype(int)

In [83]:
df = df.rename(columns = {"year_numeric":"year"})

TypeError: Series.rename() got an unexpected keyword argument 'columns'

In [ ]:
type(df)

In [ ]:
df["year"].isna().sum()

In [ ]:
df.columns

In [84]:
df = pd.read_csv("movie.csv", sep=";", encoding="cp1252")

In [85]:
df.columns

Index(['name', 'rating', 'genre', 'year', 'released', 'score', 'votes',
       'director', 'writer', 'star', 'country', 'budget', 'gross', 'company',
       'runtime'],
      dtype='object')

In [86]:
df["year_numeric"] = df["year"].astype(int)

df.rename(columns = {"year_numeric":"relesed_year"})

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,relesed_year
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0,1980
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,1980
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,1980
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,1980
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0,2001
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0,2001
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,2001
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,2001
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,2001

In [87]:
df["budget_clean"] = pd.to_numeric(df["budget"],errors = "coerce")
df["budget_clean"]

0       19000000
1        4500000
2       18000000
3        3500000
4        6000000
          ...
3995    13000000
3996           0
3997     5000000
3998    18000000
3999    70000000
Name: budget_clean, Length: 4000, dtype: int64

In [88]:
df.columns

Index(['name', 'rating', 'genre', 'year', 'released', 'score', 'votes',
       'director', 'writer', 'star', 'country', 'budget', 'gross', 'company',
       'runtime', 'year_numeric', 'budget_clean'],
      dtype='object')

In [89]:
df["rating_clean"] = df["rating"].fillna("Not Rated")
df["rating_clean"]

0        R
1        R
2       PG
3       PG
4        R
        ..
3995     R
3996     R
3997     R
3998     R
3999    PG
Name: rating_clean, Length: 4000, dtype: object

In [90]:
df["votes_clean"] = pd.to_numeric(df["votes"],errors = "coerce")
df["votes_clean"]

0        927000.0
1         65000.0
2       1200000.0
3        221000.0
4        108000.0
          ...
3995      25000.0
3996      18000.0
3997      18000.0
3998      29000.0
3999      42000.0
Name: votes_clean, Length: 4000, dtype: float64

In [91]:
df["score_clean"] = df["score"].fillna(df["score"].median())
df["score_clean"]

0       8.4
1       5.8
2       8.7
3       7.7
4       7.3
       ...
3995    6.1
3996    6.4
3997    6.4
3998    6.1
3999    4.7
Name: score_clean, Length: 4000, dtype: float64

In [92]:
df["gross_new"] = pd.to_numeric(df["gross"],errors = "coerce")
df["gross_new"]

0        46998772.0
1        58853106.0
2       538375067.0
3        83453539.0
4        39846344.0
           ...
3995     16171098.0
3996      1574660.0
3997      5480653.0
3998     13578186.0
3999    176104344.0
Name: gross_new, Length: 4000, dtype: float64

In [93]:
df["votes_clean"] = pd.to_numeric(df["votes"], errors="coerce").fillna(pd.to_numeric(df["votes"], errors="coerce").median())
df["votes_clean"]

0        927000.0
1         65000.0
2       1200000.0
3        221000.0
4        108000.0
          ...
3995      25000.0
3996      18000.0
3997      18000.0
3998      29000.0
3999      42000.0
Name: votes_clean, Length: 4000, dtype: float64

In [94]:
df["score_clean"]  = df["score"].fillna(df["score"].median())
df["score_clean"]

0       8.4
1       5.8
2       8.7
3       7.7
4       7.3
       ...
3995    6.1
3996    6.4
3997    6.4
3998    6.1
3999    4.7
Name: score_clean, Length: 4000, dtype: float64

In [95]:
df["score_ffill"] = df["score"].ffill()
df["score_ffill"]

0       8.4
1       5.8
2       8.7
3       7.7
4       7.3
       ...
3995    6.1
3996    6.4
3997    6.4
3998    6.1
3999    4.7
Name: score_ffill, Length: 4000, dtype: float64

In [96]:
df["score_bfill"] = df["score"].bfill()
df["score_bfill"]

0       8.4
1       5.8
2       8.7
3       7.7
4       7.3
       ...
3995    6.1
3996    6.4
3997    6.4
3998    6.1
3999    4.7
Name: score_bfill, Length: 4000, dtype: float64

In [97]:
df["score_filled"] = df["score"].bfill()
df["score_filled"]

0       8.4
1       5.8
2       8.7
3       7.7
4       7.3
       ...
3995    6.1
3996    6.4
3997    6.4
3998    6.1
3999    4.7
Name: score_filled, Length: 4000, dtype: float64

In [98]:
df["score_clean"] = df["score"].ffill()
df["score_clean"] = df["score_clean"].bfill()
df["score_clean"]

0       8.4
1       5.8
2       8.7
3       7.7
4       7.3
       ...
3995    6.1
3996    6.4
3997    6.4
3998    6.1
3999    4.7
Name: score_clean, Length: 4000, dtype: float64

In [179]:
df["score_final"] = df["score"].ffill().bfill().fillna(df["score"].median())
df["score_final"]

0       8.4
1       5.8
2       8.7
3       7.7
4       7.3
       ...
3995    6.1
3996    6.4
3997    6.4
3998    6.1
3999    4.7
Name: score_final, Length: 4000, dtype: float64

In [100]:
movies_unique = df.drop_duplicates()

In [101]:
df.sort_values("score",ascending = False)

,name,rating,genre,year,released,score,votes,director,writer,star,...,runtime,year_numeric,budget_clean,rating_clean,votes_clean,score_clean,gross_new,score_ffill,score_bfill,score_filled
2443,The Shawshank Redemption,R,Drama,1994,"October 14, 1994 (United States)",9.3,2400000.0,Frank Darabont,Stephen King,Tim Robbins,...,142.0,1994,25000000,R,2400000.0,9.3,28817291.0,9.3,9.3,9.3
2444,Pulp Fiction,R,Crime,1994,"October 14, 1994 (United States)",8.9,1900000.0,Quentin Tarantino,Quentin Tarantino,John Travolta,...,154.0,1994,8000000,R,1900000.0,8.9,213928762.0,8.9,8.9,8.9
2247,Schindler's List,R,Biography,1993,"February 4, 1994 (United States)",8.9,1200000.0,Steven Spielberg,Thomas Keneally,Liam Neeson,...,195.0,1993,22000000,R,1200000.0,8.9,322161245.0,8.9,8.9,8.9
2445,Forrest Gump,PG-13,Drama,1994,"July 6, 1994 (United States)",8.8,1900000.0,Robert Zemeckis,Winston Groom,Tom Hanks,...,142.0,1994,55000000,PG-13,1900000.0,8.8,678226133.0,8.8,8.8,8.8
3845,The Lord of the Rings: The Fellowship of the Ring,PG-13,Action,2001,"December 19, 2001 (United States)",8.8,1700000.0,Peter Jackson,J.R.R. Tolkien,Elijah Wood,...,178.0,2001,93000000,PG-13,1700000.0,8.8,897690072.0,8.8,8.8,8.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,Plump Fiction,R,Comedy,1997,"May 23, 1997 (Poland)",2.7,3600.0,Bob Koherr,Bob Koherr,Tommy Davidson,...,82.0,1997,0,R,3600.0,2.7,71145.0,2.7,2.7,2.7
1125,The Garbage Pail Kids Movie,PG,Adventure,1987,"August 22, 1987 (United States)",2.6,7600.0,Rod Amateau,Linda Palmer,Anthony Newley,...,100.0,1987,1000000,PG,7600.0,2.6,1576615.0,2.6,2.6,2.6
2995,Lawnmower Man 2: Beyond Cyberspace,PG-13,Action,1996,"January 12, 1996 (United States)",2.5,9000.0,Farhad Mann,Farhad Mann,Patrick Bergin,...,93.0,1996,15000000,PG-13,9000.0,2.5,2409225.0,2.5,2.5,2.5
3684,Battlefield Earth,PG-13,Action,2000,"May 12, 2000 (United States)",2.5,77000.0,Roger Christian,Corey Mandell,John Travolta,...,118.0,2000,73000000,PG-13,77000.0,2.5,29725663.0,2.5,2.5,2.5
1189,Leonard Part 6,PG,Action,1987,"December 18, 1987 (United States)",2.2,7900.0,Paul Weiland,Jonathan Reynolds,Bill Cosby,...,85.0,1987,24000000,PG,7900.0,2.2,4615255.0,2.2,2.2,2.2

In [102]:
df["score"].ffill().bfill()

0       8.4
1       5.8
2       8.7
3       7.7
4       7.3
       ...
3995    6.1
3996    6.4
3997    6.4
3998    6.1
3999    4.7
Name: score, Length: 4000, dtype: float64

In [103]:
df.columns

Index(['name', 'rating', 'genre', 'year', 'released', 'score', 'votes',
       'director', 'writer', 'star', 'country', 'budget', 'gross', 'company',
       'runtime', 'year_numeric', 'budget_clean', 'rating_clean',
       'votes_clean', 'score_clean', 'gross_new', 'score_ffill', 'score_bfill',
       'score_filled'],
      dtype='object')

In [104]:
df = pd.read_csv("movie.csv", sep=";", encoding="cp1252")

In [105]:
df.sort_values(["score", "votes"], ascending=[False, True])

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
2443,The Shawshank Redemption,R,Drama,1994,"October 14, 1994 (United States)",9.3,2400000.0,Frank Darabont,Stephen King,Tim Robbins,United States,25000000,28817291.0,Castle Rock Entertainment,142.0
2247,Schindler's List,R,Biography,1993,"February 4, 1994 (United States)",8.9,1200000.0,Steven Spielberg,Thomas Keneally,Liam Neeson,United States,22000000,322161245.0,Universal Pictures,195.0
2444,Pulp Fiction,R,Crime,1994,"October 14, 1994 (United States)",8.9,1900000.0,Quentin Tarantino,Quentin Tarantino,John Travolta,United States,8000000,213928762.0,Miramax,154.0
3845,The Lord of the Rings: The Fellowship of the Ring,PG-13,Action,2001,"December 19, 2001 (United States)",8.8,1700000.0,Peter Jackson,J.R.R. Tolkien,Elijah Wood,New Zealand,93000000,897690072.0,New Line Cinema,178.0
2445,Forrest Gump,PG-13,Drama,1994,"July 6, 1994 (United States)",8.8,1900000.0,Robert Zemeckis,Winston Groom,Tom Hanks,United States,55000000,678226133.0,Paramount Pictures,142.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3559,Baby Geniuses,PG,Comedy,1999,"March 12, 1999 (United States)",2.7,26000.0,Bob Clark,Steven Paul,Kathleen Turner,United States,12000000,36450736.0,Crystal Sky Worldwide,97.0
1125,The Garbage Pail Kids Movie,PG,Adventure,1987,"August 22, 1987 (United States)",2.6,7600.0,Rod Amateau,Linda Palmer,Anthony Newley,United States,1000000,1576615.0,Atlantic Entertainment Group,100.0
2995,Lawnmower Man 2: Beyond Cyberspace,PG-13,Action,1996,"January 12, 1996 (United States)",2.5,9000.0,Farhad Mann,Farhad Mann,Patrick Bergin,United States,15000000,2409225.0,New Line Cinema,93.0
3684,Battlefield Earth,PG-13,Action,2000,"May 12, 2000 (United States)",2.5,77000.0,Roger Christian,Corey Mandell,John Travolta,United States,73000000,29725663.0,Warner Bros.,118.0
1189,Leonard Part 6,PG,Action,1987,"December 18, 1987 (United States)",2.2,7900.0,Paul Weiland,Jonathan Reynolds,Bill Cosby,United States,24000000,4615255.0,Columbia Pictures,85.0

In [106]:
df.columns

Index(['name', 'rating', 'genre', 'year', 'released', 'score', 'votes',
       'director', 'writer', 'star', 'country', 'budget', 'gross', 'company',
       'runtime'],
      dtype='object')

In [107]:
df.sort_values(["score"],ascending = False).head(5)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
2443,The Shawshank Redemption,R,Drama,1994,"October 14, 1994 (United States)",9.3,2400000.0,Frank Darabont,Stephen King,Tim Robbins,United States,25000000,28817291.0,Castle Rock Entertainment,142.0
2444,Pulp Fiction,R,Crime,1994,"October 14, 1994 (United States)",8.9,1900000.0,Quentin Tarantino,Quentin Tarantino,John Travolta,United States,8000000,213928762.0,Miramax,154.0
2247,Schindler's List,R,Biography,1993,"February 4, 1994 (United States)",8.9,1200000.0,Steven Spielberg,Thomas Keneally,Liam Neeson,United States,22000000,322161245.0,Universal Pictures,195.0
2445,Forrest Gump,PG-13,Drama,1994,"July 6, 1994 (United States)",8.8,1900000.0,Robert Zemeckis,Winston Groom,Tom Hanks,United States,55000000,678226133.0,Paramount Pictures,142.0
3845,The Lord of the Rings: The Fellowship of the Ring,PG-13,Action,2001,"December 19, 2001 (United States)",8.8,1700000.0,Peter Jackson,J.R.R. Tolkien,Elijah Wood,New Zealand,93000000,897690072.0,New Line Cinema,178.0

In [108]:
df.sort_values("votes", ascending = False).head(5)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
2443,The Shawshank Redemption,R,Drama,1994,"October 14, 1994 (United States)",9.3,2400000.0,Frank Darabont,Stephen King,Tim Robbins,United States,25000000,28817291.0,Castle Rock Entertainment,142.0
2444,Pulp Fiction,R,Crime,1994,"October 14, 1994 (United States)",8.9,1900000.0,Quentin Tarantino,Quentin Tarantino,John Travolta,United States,8000000,213928762.0,Miramax,154.0
2445,Forrest Gump,PG-13,Drama,1994,"July 6, 1994 (United States)",8.8,1900000.0,Robert Zemeckis,Winston Groom,Tom Hanks,United States,55000000,678226133.0,Paramount Pictures,142.0
3444,Fight Club,R,Drama,1999,"October 15, 1999 (United States)",8.8,1900000.0,David Fincher,Chuck Palahniuk,Brad Pitt,Germany,63000000,101209702.0,Fox 2000 Pictures,139.0
3443,The Matrix,R,Action,1999,"March 31, 1999 (United States)",8.7,1700000.0,Lana Wachowski,Lilly Wachowski,Keanu Reeves,United States,63000000,466364845.0,Warner Bros.,136.0

In [109]:
df.groupby("genre")["score"].mean()

genre
Action       6.014968
Adventure    6.151948
Animation    6.883186
Biography    7.052000
Comedy       6.179410
Crime        6.645033
Drama        6.673606
Family       6.550000
Fantasy      6.024242
History      8.300000
Horror       5.744304
Music        7.200000
Mystery      6.500000
Romance      6.400000
Sci-Fi       5.983333
Thriller     5.890909
Western      5.666667
Name: score, dtype: float64

In [110]:
df.groupby("genre")["name"].count()

genre
Action        775
Adventure     231
Animation     113
Biography     175
Comedy       1355
Crime         302
Drama         807
Family          8
Fantasy        33
History         1
Horror        158
Music           1
Mystery        13
Romance         8
Sci-Fi          6
Thriller       11
Western         3
Name: name, dtype: int64

In [111]:
df.groupby("genre")["score"].max()

genre
Action       8.8
Adventure    8.5
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        8.9
Drama        9.3
Family       7.8
Fantasy      7.6
History      8.3
Horror       8.1
Music        7.2
Mystery      8.4
Romance      7.8
Sci-Fi       6.4
Thriller     6.6
Western      6.4
Name: score, dtype: float64

In [112]:
df.groupby("genre")["score"].min()

genre
Action       2.2
Adventure    2.6
Animation    4.2
Biography    3.7
Comedy       2.7
Crime        4.0
Drama        2.7
Family       5.9
Fantasy      4.2
History      8.3
Horror       2.9
Music        7.2
Mystery      5.0
Romance      4.2
Sci-Fi       5.3
Thriller     4.6
Western      5.1
Name: score, dtype: float64

In [113]:
df.groupby("genre")["score"].agg(["mean","max"])

               mean  max
genre
Action     6.014968  8.8
Adventure  6.151948  8.5
Animation  6.883186  8.6
Biography  7.052000  8.9
Comedy     6.179410  8.6
Crime      6.645033  8.9
Drama      6.673606  9.3
Family     6.550000  7.8
Fantasy    6.024242  7.6
History    8.300000  8.3
Horror     5.744304  8.1
Music      7.200000  7.2
Mystery    6.500000  8.4
Romance    6.400000  7.8
Sci-Fi     5.983333  6.4
Thriller   5.890909  6.6
Western    5.666667  6.4

In [114]:
df.groupby("genre").agg({"score":"mean", "votes":"sum"})

              score       votes
genre
Action     6.014968  60294155.0
Adventure  6.151948  13539506.0
Animation  6.883186  11841788.0
Biography  7.052000  10855318.0
Comedy     6.179410  46704518.0
Crime      6.645033  22012705.0
Drama      6.673606  41455729.0
Family     6.550000    443400.0
Fantasy    6.024242   1769400.0
History    8.300000        79.0
Horror     5.744304   6597068.0
Music      7.200000     12000.0
Mystery    6.500000   2282515.0
Romance    6.400000     76974.0
Sci-Fi     5.983333     33765.0
Thriller   5.890909     52891.0
Western    5.666667      6199.0

In [115]:
df["genre_avg_score"] = df.groupby("genre")["score"].transform("mean")
df["genre_avg_score"]

0       6.673606
1       6.151948
2       6.014968
3       6.179410
4       6.179410
          ...
3995    6.179410
3996    6.179410
3997    6.179410
3998    6.179410
3999    6.179410
Name: genre_avg_score, Length: 4000, dtype: float64

In [116]:
df.groupby("genre")["score"].transform("mean")

0       6.673606
1       6.151948
2       6.014968
3       6.179410
4       6.179410
          ...
3995    6.179410
3996    6.179410
3997    6.179410
3998    6.179410
3999    6.179410
Name: score, Length: 4000, dtype: float64

In [117]:
df["genre_max_score"] = df.groupby("genre")["score"].transform("max")
df["genre_max_score"]

0       9.3
1       8.5
2       8.8
3       8.6
4       8.6
       ...
3995    8.6
3996    8.6
3997    8.6
3998    8.6
3999    8.6
Name: genre_max_score, Length: 4000, dtype: float64

In [118]:
df.groupby("genre").filter(lambda x: len(x) >100)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,genre_avg_score,genre_max_score
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0,6.673606,9.3
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,6.151948,8.5
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,6.014968,8.8
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,6.179410,8.6
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,6.179410,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0,6.179410,8.6
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0,6.179410,8.6
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,6.179410,8.6
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,6.179410,8.6
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,6.179410,8.6

In [119]:
df.groupby(["genre","country"])["votes"].sum()

genre     country
Action    Aruba              14000.0
          Australia         562500.0
          Austria            52000.0
          Canada            229553.0
          Denmark             5300.0
                              ...
Thriller  United Kingdom     13300.0
          United States      25309.0
Western   Italy                499.0
          United Kingdom      4200.0
          United States       1500.0
Name: votes, Length: 176, dtype: float64

In [120]:
df.groupby(["genre","country"],as_index = False)["score"].mean()

        genre         country     score
0      Action           Aruba  4.900000
1      Action       Australia  6.133333
2      Action         Austria  6.400000
3      Action          Canada  5.215385
4      Action         Denmark  5.400000
..        ...             ...       ...
171  Thriller  United Kingdom  6.433333
172  Thriller   United States  5.780000
173   Western           Italy  5.100000
174   Western  United Kingdom  5.500000
175   Western   United States  6.400000

[176 rows x 3 columns]

In [121]:
result = df.groupby("genre",as_index = False).agg({"score":"mean","votes":"sum"}).sort_values("score",ascending = False)

result

        genre     score       votes
9     History  8.300000        79.0
11      Music  7.200000     12000.0
3   Biography  7.052000  10855318.0
2   Animation  6.883186  11841788.0
6       Drama  6.673606  41455729.0
5       Crime  6.645033  22012705.0
7      Family  6.550000    443400.0
12    Mystery  6.500000   2282515.0
13    Romance  6.400000     76974.0
4      Comedy  6.179410  46704518.0
1   Adventure  6.151948  13539506.0
8     Fantasy  6.024242   1769400.0
0      Action  6.014968  60294155.0
14     Sci-Fi  5.983333     33765.0
15   Thriller  5.890909     52891.0
10     Horror  5.744304   6597068.0
16    Western  5.666667      6199.0

In [122]:
df.sort_values("score",ascending=False).groupby("genre").head(3)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,genre_avg_score,genre_max_score
2443,The Shawshank Redemption,R,Drama,1994,"October 14, 1994 (United States)",9.3,2400000.0,Frank Darabont,Stephen King,Tim Robbins,United States,25000000,2.881729e+07,Castle Rock Entertainment,142.0,6.673606,9.3
2444,Pulp Fiction,R,Crime,1994,"October 14, 1994 (United States)",8.9,1900000.0,Quentin Tarantino,Quentin Tarantino,John Travolta,United States,8000000,2.139288e+08,Miramax,154.0,6.645033,8.9
2247,Schindler's List,R,Biography,1993,"February 4, 1994 (United States)",8.9,1200000.0,Steven Spielberg,Thomas Keneally,Liam Neeson,United States,22000000,3.221612e+08,Universal Pictures,195.0,7.052000,8.9
2445,Forrest Gump,PG-13,Drama,1994,"July 6, 1994 (United States)",8.8,1900000.0,Robert Zemeckis,Winston Groom,Tom Hanks,United States,55000000,6.782261e+08,Paramount Pictures,142.0,6.673606,9.3
3845,The Lord of the Rings: The Fellowship of the Ring,PG-13,Action,2001,"December 19, 2001 (United States)",8.8,1700000.0,Peter Jackson,J.R.R. Tolkien,Elijah Wood,New Zealand,93000000,8.976901e+08,New Line Cinema,178.0,6.014968,8.8
3444,Fight Club,R,Drama,1999,"October 15, 1999 (United States)",8.8,1900000.0,David Fincher,Chuck Palahniuk,Brad Pitt,Germany,63000000,1.012097e+08,Fox 2000 Pictures,139.0,6.673606,9.3
1643,Goodfellas,R,Biography,1990,"September 21, 1990 (United States)",8.7,1100000.0,Martin Scorsese,Nicholas Pileggi,Robert De Niro,United States,25000000,4.696328e+07,Warner Bros.,146.0,7.052000,8.9
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,5.383751e+08,Lucasfilm,124.0,6.014968,8.8
3443,The Matrix,R,Action,1999,"March 31, 1999 (United States)",8.7,1700000.0,Lana Wachowski,Lilly Wachowski,Keanu Reeves,United States,63000000,4.663648e+08,Warner Bros.,136.0,6.014968,8.8
2645,Se7en,R,Crime,1995,"September 22, 1995 (United States)",8.6,1500000.0,David Fincher,Andrew Kevin Walker,Morgan Freeman,United States,33000000,3.273336e+08,Cecchi Gori Pictures,127.0,6.645033,8.9
3849,Spirited Away,PG,Animation,2001,"March 28, 2003 (United States)",8.6,679000.0,Hayao Miyazaki,Hayao Miyazaki,Daveigh Chase,Japan,19000000,3.554752e+08,Tokuma Shoten,125.0,6.883186,8.6
3449,The Green Mile,R,Crime,1999,"December 10, 1999 (United States)",8.6,1200000.0,Frank Darabont,Stephen King,Tom Hanks,United States,60000000,2.868014e+08,Castle Rock Entertainment,189.0,6.645033,8.9
3055,Life Is Beautiful,PG-13,Comedy,1997,"December 20, 1997 (Italy)",8.6,642000.0,Roberto Benigni,Vincenzo Cerami,Roberto Benigni,Italy,20000000,2.300988e+08,Melampo Cinematografica,116.0,6.179410,8.6
645,Back to the Future,PG,Adventure,1985,"July 3, 1985 (United States)",8.5,1100000.0,Robert Zemeckis,Robert Zemeckis,Michael J. Fox,United States,19000000,3.819068e+08,Universal Pictures,116.0,6.151948,8.5
2448,The Lion King,G,Animation,1994,"June 24, 1994 (United States)",8.5,970000.0,Roger Allers,Irene Mecchi,Matthew Broderick,United States,45000000,1.083721e+09,Walt Disney Pictures,88.0,6.883186,8.6
3065,Princess Mononoke,PG-13,Animation,1997,"December 19, 1997 (United States)",8.4,357000.0,Hayao Miyazaki,Hayao Miyazaki,Yôji Matsuda,Japan,0,1.697857e+08,DENTSU Music And Entertainment,134.0,6.883186,8.6
3648,Memento,R,Mystery,2000,"May 25, 2001 (United States)",8.4,1200000.0,Christopher Nolan,Christopher Nolan,Guy Pearce,United States,9000000,4.004708e+07,Newmarket Capital Group,113.0,6.500000,8.4
474,The Business of Show Business,NaN,History,1983,"February 15, 1983 (Canada)",8.3,79.0,Tom Logan,Tom Logan,NaN,Canada,323562,NaN,CTV,55.0,8.300000,8.3
49,Lion of the Desert,PG,Biography,1980,"May 16, 1981 (Japan)",8.3,15000.0,Moustapha Akkad,David Butler,Anthony Quinn,Libya,35000000,NaN,Falcon International Productions,173.0,7.052000,8.9
3860,Amélie,R,Comedy,2001,"February 8, 2002 (United States)",8.3,717000.0,Jean-Pierre Jeunet,Guillaume Laurant,Audrey Tautou,France,10000000,1.739971e+08,Claudie Ossard Productions,122.0,6.179410,8.6
3646,Snatch,R,Comedy,2000,"January 19, 2001 (United States)",8.3,800000.0,Guy Ritchie,Guy Ritchie,Jason Statham,United Kingdom,0,8.355787e+07,Columbia Pictures,102.0,6.179410,8.6
102,Das Boot,NaN,Adventure,1981,"February 10, 1982 (United States)",8.3,237000.0,Wolfgang Petersen,Wolfgang Petersen,Jürgen Prochnow,West Germany,0,1.148768e+07,Bavaria Film,149.0,6.151948,8.5
845,Stand by Me,R,Adventure,1986,"August 22, 1986 (United States)",8.1,374000.0,Rob Reiner,Stephen King,Wil Wheaton,United States,8000000,5.228741e+07,Columbia Pictures,89.0,6.151948,8.5
207,The Thing,R,Horror,1982,"June 25, 1982 (United States)",8.1,382000.0,John Carpenter,Bill Lancaster,Kurt Russell,United States,15000000,1.963205e+07,Universal Pictures,109.0,5.744304,8.1
2659,12 Monkeys,R,Mystery,1995,"January 5, 1996 (United States)",8.0,589000.0,Terry Gilliam,Chris Marker,Bruce Willis,United States,29000001,1.688395e+08,Universal Pictures,129.0,6.500000,8.4
209,E.T. the Extra-Terrestrial,PG,Family,1982,"June 11, 1982 (United States)",7.8,381000.0,Steven Spielberg,Melissa Mathison,Henry Thomas,United States,10500000,7.929106e+08,Universal Pictures,115.0,6.550000,7.8
3616,The Piano Player,Not Rated,Romance,1999,"October 21, 1999 (Germany)",7.8,7400.0,Rolf Schübel,Ruth Toma,Joachim Król,Germany,0,6.465320e+05,Studio Hamburg Filmproduktion,112.0,6.400000,7.8
3271,Dark City,R,Fantasy,1998,"February 27, 1998 (United States)",7.6,191000.0,Alex Proyas,Alex Proyas,Rufus Sewell,Australia,27000000,2.720032e+07,Mystery Clock Cinema,100.0,6.024242,7.6
3873,The Others,PG-13,Horror,2001,"August 10, 2001 (United States)",7.6,346000.0,Alejandro Amenábar,Alejandro Amenábar,Nicole Kidman,Spain,17000000,2.099470e+08,Cruise/Wagner Productions,104.0,5.744304,8.1
3088,Lost Highway,R,Mystery,1997,"January 15, 1997 (France)",7.6,134000.0,David Lynch,David Lynch,Bill Pullman,France,15000000,3.703548e+06,CiBy 2000,134.0,6.500000,8.4
2702,The City of Lost Children,R,Fantasy,1995,"December 15, 1995 (United States)",7.5,66000.0,Marc Caro,Gilles Adrien,Ron Perlman,France,18000000,1.781465e+06,Constellation,112.0,6.024242,7.6
483,A Nightmare on Elm Street,R,Horror,1984,"November 16, 1984 (United States)",7.5,212000.0,Wes Craven,Wes Craven,Heather Langenkamp,United States,1800000,2.550714e+07,New Line Cinema,91.0,5.744304,8.1
3468,Sleepy Hollow,R,Fantasy,1999,"November 19, 1999 (United States)",7.3,338000.0,Tim Burton,Washington Irving,Johnny Depp,United States,100000000,2.060715e+08,Paramount Pictures,105.0,6.024242,7.6
1029,Nutcracker,G,Family,1986,"November 26, 1986 (United States)",7.2,1000.0,Carroll Ballard,Kent Stowell,Hugh Duncan Bigney Mitchell,United States,0,7.817270e+05,Hyperion Pictures,89.0,6.550000,7.8
162,Diva,R,Music,1981,"April 23, 1982 (United States)",7.2,12000.0,Jean-Jacques Beineix,Daniel Odier,Wilhelmenia Fernandez,France,0,1.100140e+05,Les Films Galaxie,117.0,7.200000,7.2
156,Eye of the Needle,R,Romance,1981,"July 24, 1981 (United States)",7.1,9900.0,Richard Marquand,Ken Follett,Donald Sutherland,United Kingdom,0,1.758363e+07,Kings Road Entertainment,112.0,6.400000,7.8
3820,The House of Mirth,PG,Romance,2000,"October 13, 2000 (United Kingdom)",7.0,7200.0,Terence Davies,Edith Wharton,Gillian Anderson,United Kingdom,10000000,5.164404e+06,Three Rivers Production,135.0,6.400000,7.8
754,Subway,R,Thriller,1985,"November 6, 1985 (United States)",6.6,14000.0,Luc Besson,Luc Besson,Christopher Lambert,France,0,3.906590e+05,Les Films du Loup,104.0,5.890909,6.6
430,The Lords of Discipline,R,Thriller,1983,"February 18, 1983 (United States)",6.6,2600.0,Franc Roddam,Pat Conroy,David Keith,United States,0,1.178713e+07,Paramount Pictures,102.0,5.890909,6.6
1149,The Fourth Protocol,R,Thriller,1987,"August 28, 1987 (United States)",6.6,9200.0,John Mackenzie,George Axelrod,Michael Caine,United Kingdom,6000000,1.242383e+07,Fourth Protocol,119.0,5.890909,6.6
2554,Miracle on 34th Street,PG,Family,1994,"November 18, 1994 (United States)",6.5,33000.0,Les Mayfield,Valentine Davies,Richard Attenborough,United States,0,4.626438e+07,Twentieth Century Fox,114.0,6.550000,7.8
390,Brainstorm,PG,Sci-Fi,1983,"September 30, 1983 (United States)",6.4,11000.0,Douglas Trumbull,Bruce Joel Rubin,Christopher Walken,United States,15000000,1.021946e+07,JF Productions,106.0,5.983333,6.4
287,Barbarosa,PG,Western,1982,"February 19, 1982 (United States)",6.4,1500.0,Fred Schepisi,William D. Wittliff,Willie Nelson,United States,11000000,1.736123e+06,Incorporated Television Company (ITC),90.0,5.666667,6.4
942,The Manhattan Project,PG-13,Sci-Fi,1986,"June 13, 1986 (United States)",6.2,5600.0,Marshall Brickman,Marshall Brickman,John Lithgow,United States,18000000,3.900000e+06,Gladden Entertainment,117.0,5.983333,6.4
299,Jekyll and Hyde... Together Again,R,Sci-Fi,1982,"October 1, 1982 (United States)",6.2,1100.0,Jerry Belson,Monica Mcgowan Johnson,Mark Blankfield,United States,5000000,3.792188e+06,Paramount Pictures,87.0,5.983333,6.4
2382,Posse,R,Western,1993,"May 14, 1993 (United States)",5.5,4200.0,Mario Van Peebles,Sy Richardson,Mario Van Peebles,United Kingdom,10000000,1.828976e+07,PolyGram Filmed Entertainment,111.0,5.666667,6.4
202,Comin' at Ya!,R,Western,1981,"July 24, 1981 (United States)",5.1,499.0,Ferdinando Baldi,Wolfe Lowenthal,Tony Anthony,Italy,0,1.200000e+07,Lupo-Anthony-Quintano Productions,91.0,5.666667,6.4

In [123]:
df.sort_values("votes",ascending=False).groupby("genre").head(2)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,genre_avg_score,genre_max_score
2443,The Shawshank Redemption,R,Drama,1994,"October 14, 1994 (United States)",9.3,2400000.0,Frank Darabont,Stephen King,Tim Robbins,United States,25000000,2.881729e+07,Castle Rock Entertainment,142.0,6.673606,9.3
2444,Pulp Fiction,R,Crime,1994,"October 14, 1994 (United States)",8.9,1900000.0,Quentin Tarantino,Quentin Tarantino,John Travolta,United States,8000000,2.139288e+08,Miramax,154.0,6.645033,8.9
2445,Forrest Gump,PG-13,Drama,1994,"July 6, 1994 (United States)",8.8,1900000.0,Robert Zemeckis,Winston Groom,Tom Hanks,United States,55000000,6.782261e+08,Paramount Pictures,142.0,6.673606,9.3
3443,The Matrix,R,Action,1999,"March 31, 1999 (United States)",8.7,1700000.0,Lana Wachowski,Lilly Wachowski,Keanu Reeves,United States,63000000,4.663648e+08,Warner Bros.,136.0,6.014968,8.8
3845,The Lord of the Rings: The Fellowship of the Ring,PG-13,Action,2001,"December 19, 2001 (United States)",8.8,1700000.0,Peter Jackson,J.R.R. Tolkien,Elijah Wood,New Zealand,93000000,8.976901e+08,New Line Cinema,178.0,6.014968,8.8
2645,Se7en,R,Crime,1995,"September 22, 1995 (United States)",8.6,1500000.0,David Fincher,Andrew Kevin Walker,Morgan Freeman,United States,33000000,3.273336e+08,Cecchi Gori Pictures,127.0,6.645033,8.9
2247,Schindler's List,R,Biography,1993,"February 4, 1994 (United States)",8.9,1200000.0,Steven Spielberg,Thomas Keneally,Liam Neeson,United States,22000000,3.221612e+08,Universal Pictures,195.0,7.052000,8.9
3648,Memento,R,Mystery,2000,"May 25, 2001 (United States)",8.4,1200000.0,Christopher Nolan,Christopher Nolan,Guy Pearce,United States,9000000,4.004708e+07,Newmarket Capital Group,113.0,6.500000,8.4
645,Back to the Future,PG,Adventure,1985,"July 3, 1985 (United States)",8.5,1100000.0,Robert Zemeckis,Robert Zemeckis,Michael J. Fox,United States,19000000,3.819068e+08,Universal Pictures,116.0,6.151948,8.5
1643,Goodfellas,R,Biography,1990,"September 21, 1990 (United States)",8.7,1100000.0,Martin Scorsese,Nicholas Pileggi,Robert De Niro,United States,25000000,4.696328e+07,Warner Bros.,146.0,7.052000,8.9
3247,The Truman Show,PG,Comedy,1998,"June 5, 1998 (United States)",8.1,972000.0,Peter Weir,Andrew Niccol,Jim Carrey,United States,60000000,2.641182e+08,Paramount Pictures,103.0,6.179410,8.6
2448,The Lion King,G,Animation,1994,"June 24, 1994 (United States)",8.5,970000.0,Roger Allers,Irene Mecchi,Matthew Broderick,United States,45000000,1.083721e+09,Walt Disney Pictures,88.0,6.883186,8.6
2654,Toy Story,G,Animation,1995,"November 22, 1995 (United States)",8.3,913000.0,John Lasseter,John Lasseter,Tom Hanks,United States,30000000,3.944366e+08,Walt Disney Pictures,81.0,6.883186,8.6
3646,Snatch,R,Comedy,2000,"January 19, 2001 (United States)",8.3,800000.0,Guy Ritchie,Guy Ritchie,Jason Statham,United Kingdom,0,8.355787e+07,Columbia Pictures,102.0,6.179410,8.6
3843,Harry Potter and the Sorcerer's Stone,PG,Adventure,2001,"November 16, 2001 (United States)",7.6,685000.0,Chris Columbus,J.K. Rowling,Daniel Radcliffe,United Kingdom,125000000,1.006968e+09,Warner Bros.,152.0,6.151948,8.5
2659,12 Monkeys,R,Mystery,1995,"January 5, 1996 (United States)",8.0,589000.0,Terry Gilliam,Chris Marker,Bruce Willis,United States,29000001,1.688395e+08,Universal Pictures,129.0,6.500000,8.4
207,The Thing,R,Horror,1982,"June 25, 1982 (United States)",8.1,382000.0,John Carpenter,Bill Lancaster,Kurt Russell,United States,15000000,1.963205e+07,Universal Pictures,109.0,5.744304,8.1
209,E.T. the Extra-Terrestrial,PG,Family,1982,"June 11, 1982 (United States)",7.8,381000.0,Steven Spielberg,Melissa Mathison,Henry Thomas,United States,10500000,7.929106e+08,Universal Pictures,115.0,6.550000,7.8
3873,The Others,PG-13,Horror,2001,"August 10, 2001 (United States)",7.6,346000.0,Alejandro Amenábar,Alejandro Amenábar,Nicole Kidman,Spain,17000000,2.099470e+08,Cruise/Wagner Productions,104.0,5.744304,8.1
3468,Sleepy Hollow,R,Fantasy,1999,"November 19, 1999 (United States)",7.3,338000.0,Tim Burton,Washington Irving,Johnny Depp,United States,100000000,2.060715e+08,Paramount Pictures,105.0,6.024242,7.6
3870,Vanilla Sky,R,Fantasy,2001,"December 14, 2001 (United States)",6.9,253000.0,Cameron Crowe,Alejandro Amenábar,Tom Cruise,United States,68000000,2.033883e+08,Paramount Pictures,136.0,6.024242,7.6
521,Starman,PG,Romance,1984,"December 14, 1984 (United States)",7.0,44000.0,John Carpenter,Bruce A. Evans,Jeff Bridges,United States,22000000,2.874436e+07,Columbia Pictures,115.0,6.400000,7.8
2554,Miracle on 34th Street,PG,Family,1994,"November 18, 1994 (United States)",6.5,33000.0,Les Mayfield,Valentine Davies,Richard Attenborough,United States,0,4.626438e+07,Twentieth Century Fox,114.0,6.550000,7.8
1701,Pacific Heights,R,Thriller,1990,"September 28, 1990 (United States)",6.4,19000.0,John Schlesinger,Daniel Pyne,Melanie Griffith,United States,18000000,4.492671e+07,Morgan Creek Entertainment,102.0,5.890909,6.6
754,Subway,R,Thriller,1985,"November 6, 1985 (United States)",6.6,14000.0,Luc Besson,Luc Besson,Christopher Lambert,France,0,3.906590e+05,Les Films du Loup,104.0,5.890909,6.6
1726,Hardware,R,Sci-Fi,1990,"September 14, 1990 (United States)",6.0,13000.0,Richard Stanley,Steve MacManus,Dylan McDermott,United Kingdom,1500000,5.728953e+06,Palace Pictures,94.0,5.983333,6.4
162,Diva,R,Music,1981,"April 23, 1982 (United States)",7.2,12000.0,Jean-Jacques Beineix,Daniel Odier,Wilhelmenia Fernandez,France,0,1.100140e+05,Les Films Galaxie,117.0,7.200000,7.2
390,Brainstorm,PG,Sci-Fi,1983,"September 30, 1983 (United States)",6.4,11000.0,Douglas Trumbull,Bruce Joel Rubin,Christopher Walken,United States,15000000,1.021946e+07,JF Productions,106.0,5.983333,6.4
156,Eye of the Needle,R,Romance,1981,"July 24, 1981 (United States)",7.1,9900.0,Richard Marquand,Ken Follett,Donald Sutherland,United Kingdom,0,1.758363e+07,Kings Road Entertainment,112.0,6.400000,7.8
2382,Posse,R,Western,1993,"May 14, 1993 (United States)",5.5,4200.0,Mario Van Peebles,Sy Richardson,Mario Van Peebles,United Kingdom,10000000,1.828976e+07,PolyGram Filmed Entertainment,111.0,5.666667,6.4
287,Barbarosa,PG,Western,1982,"February 19, 1982 (United States)",6.4,1500.0,Fred Schepisi,William D. Wittliff,Willie Nelson,United States,11000000,1.736123e+06,Incorporated Television Company (ITC),90.0,5.666667,6.4
474,The Business of Show Business,NaN,History,1983,"February 15, 1983 (Canada)",8.3,79.0,Tom Logan,Tom Logan,NaN,Canada,323562,NaN,CTV,55.0,8.300000,8.3

In [124]:
df.groupby("genre",as_index=False).agg({"votes":"sum","score":"mean"})

        genre       votes     score
0      Action  60294155.0  6.014968
1   Adventure  13539506.0  6.151948
2   Animation  11841788.0  6.883186
3   Biography  10855318.0  7.052000
4      Comedy  46704518.0  6.179410
5       Crime  22012705.0  6.645033
6       Drama  41455729.0  6.673606
7      Family    443400.0  6.550000
8     Fantasy   1769400.0  6.024242
9     History        79.0  8.300000
10     Horror   6597068.0  5.744304
11      Music     12000.0  7.200000
12    Mystery   2282515.0  6.500000
13    Romance     76974.0  6.400000
14     Sci-Fi     33765.0  5.983333
15   Thriller     52891.0  5.890909
16    Western      6199.0  5.666667

In [125]:
df.groupby("genre").filter(lambda x: (len(x) > 100) & (x["score"].mean() > 7))

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,genre_avg_score,genre_max_score
7,Raging Bull,R,Biography,1980,"December 19, 1980 (United States)",8.2,330000.0,Martin Scorsese,Jake LaMotta,Robert De Niro,United States,18000000,23402427.0,Chartoff-Winkler Productions,129.0,7.052,8.9
9,The Long Riders,R,Biography,1980,"May 16, 1980 (United States)",7.0,10000.0,Walter Hill,Bill Bryden,David Carradine,United States,10000000,15795189.0,United Artists,100.0,7.052,8.9
39,Coal Miner's Daughter,PG,Biography,1980,"March 7, 1980 (United States)",7.5,17000.0,Michael Apted,Thomas Rickman,Sissy Spacek,United States,0,67182787.0,Universal Pictures,124.0,7.052,8.9
43,Where the Buffalo Roam,R,Biography,1980,"April 25, 1980 (United States)",6.6,11000.0,Art Linson,Hunter S. Thompson,Peter Boyle,United States,0,6659377.0,Universal Pictures,99.0,7.052,8.9
49,Lion of the Desert,PG,Biography,1980,"May 16, 1981 (Japan)",8.3,15000.0,Moustapha Akkad,David Butler,Anthony Quinn,Libya,35000000,NaN,Falcon International Productions,173.0,7.052,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3894,Bully,TV-MA,Biography,2001,"December 12, 2001 (France)",6.9,35000.0,Larry Clark,Jim Schutze,Brad Renfro,United States,0,704808.0,StudioCanal,108.0,7.052,8.9
3907,Riding in Cars with Boys,PG-13,Biography,2001,"October 19, 2001 (United States)",6.5,27000.0,Penny Marshall,Beverly D'Onofrio,Drew Barrymore,United States,48000000,35743308.0,Columbia Pictures,132.0,7.052,8.9
3942,Ali,R,Biography,2001,"December 25, 2001 (United States)",6.8,95000.0,Michael Mann,Gregory Allen Howard,Will Smith,United States,107000000,87812729.0,Columbia Pictures,157.0,7.052,8.9
3984,Iris,R,Biography,2001,"March 29, 2002 (United States)",7.0,18000.0,Richard Eyre,John Bayley,Judi Dench,United Kingdom,5500000,16153953.0,British Broadcasting Corporation (BBC),91.0,7.052,8.9
3985,Nowhere in Africa,R,Biography,2001,"May 16, 2003 (United States)",7.5,13000.0,Caroline Link,Caroline Link,Juliane Köhler,Germany,0,24322180.0,"BKM, kulturelle Filmförderung des Bundes",141.0,7.052,8.9

In [126]:
df["profit"] = df["gross"] - df["budget"]
df["profit"]

0        27998772.0
1        54353106.0
2       520375067.0
3        79953539.0
4        33846344.0
           ...
3995      3171098.0
3996      1574660.0
3997       480653.0
3998     -4421814.0
3999    106104344.0
Name: profit, Length: 4000, dtype: float64

In [128]:
df["profit_margin"] = df["profit"] / df["gross"]
df["profit_margin"]

0       0.595734
1       0.923538
2       0.966566
3       0.958060
4       0.849422
          ...
3995    0.196097
3996    1.000000
3997    0.087700
3998   -0.325656
3999    0.602508
Name: profit_margin, Length: 4000, dtype: float64

In [133]:
import numpy as np
df["score_category"] = np.where(df["score"] >= 8,"high","low")
df["score_category"]

0       high
1        low
2       high
3        low
4        low
        ...
3995     low
3996     low
3997     low
3998     low
3999     low
Name: score_category, Length: 4000, dtype: object

In [136]:
df["profit_status"] = np.where(df["profit"] >=0,"profit","loss")
df["profit_status"]

0       profit
1       profit
2       profit
3       profit
4       profit
         ...
3995    profit
3996    profit
3997    profit
3998      loss
3999    profit
Name: profit_status, Length: 4000, dtype: object

In [143]:
def classify_movies(runtime):
    if runtime >=150:
        return "long"
    elif runtime >=90:
        return "medium"
    else:
        return "short"

df["runtime_movies"] = df["runtime"].apply(classify_movies)
df["runtime_movies"]

0       medium
1       medium
2       medium
3        short
4       medium
         ...
3995    medium
3996    medium
3997    medium
3998    medium
3999     short
Name: runtime_movies, Length: 4000, dtype: object

In [146]:
def movies(runtime):
    if runtime >=120:
        return "long"
    elif runtime >=90:
        return "medium"
    else:
        return "short"

df["movie_type"] = df["runtime"].apply(movies)
df["movie_type"]

0         long
1       medium
2         long
3        short
4       medium
         ...
3995    medium
3996    medium
3997    medium
3998    medium
3999     short
Name: movie_type, Length: 4000, dtype: object

In [148]:
df["score_plus_one"] = df["score"].apply(lambda x: x + 1)
df["score_plus_one"]

0       9.4
1       6.8
2       9.7
3       8.7
4       8.3
       ...
3995    7.1
3996    7.4
3997    7.4
3998    7.1
3999    5.7
Name: score_plus_one, Length: 4000, dtype: float64

In [151]:
genre_map = {"Action" : "A","Comedy" : "C","Drama":"D","Horror":"H"}
df["genre_code"] = df["genre"].map(genre_map)
df["genre_code"]

0         D
1       NaN
2         A
3         C
4         C
       ...
3995      C
3996      C
3997      C
3998      C
3999      C
Name: genre_code, Length: 4000, dtype: object

In [153]:
df["name_upper"] = df["name"].str.upper()
df["name_upper"]

0                                          THE SHINING
1                                      THE BLUE LAGOON
2       STAR WARS: EPISODE V - THE EMPIRE STRIKES BACK
3                                            AIRPLANE!
4                                           CADDYSHACK
                             ...
3995                                     BIRTHDAY GIRL
3996                                      HUMAN NATURE
3997                                              MADE
3998                             ONE NIGHT AT MCCOOL'S
3999                                    DR. DOLITTLE 2
Name: name_upper, Length: 4000, dtype: object

In [156]:
df["name_lower"] = df["name"].str.lower()
df["name_lower"]

0                                          the shining
1                                      the blue lagoon
2       star wars: episode v - the empire strikes back
3                                            airplane!
4                                           caddyshack
                             ...
3995                                     birthday girl
3996                                      human nature
3997                                              made
3998                             one night at mccool's
3999                                    dr. dolittle 2
Name: name_lower, Length: 4000, dtype: object

In [157]:
df["names_len"] = df["name"].str.len()
df["names_len"]

0       11
1       15
2       46
3        9
4       10
        ..
3995    13
3996    12
3997     4
3998    21
3999    14
Name: names_len, Length: 4000, dtype: int64

In [159]:
df["name_clean"] = df["name"].str.strip()
df["name_clean"]

0                                          The Shining
1                                      The Blue Lagoon
2       Star Wars: Episode V - The Empire Strikes Back
3                                            Airplane!
4                                           Caddyshack
                             ...
3995                                     Birthday Girl
3996                                      Human Nature
3997                                              Made
3998                             One Night at McCool's
3999                                    Dr. Dolittle 2
Name: name_clean, Length: 4000, dtype: object

In [162]:
df["name_no_colon"] = df["name"].str.replace(":","",regex=False)
df["name_no_colon"]

0                                         The Shining
1                                     The Blue Lagoon
2       Star Wars Episode V - The Empire Strikes Back
3                                           Airplane!
4                                          Caddyshack
                            ...
3995                                    Birthday Girl
3996                                     Human Nature
3997                                             Made
3998                            One Night at McCool's
3999                                   Dr. Dolittle 2
Name: name_no_colon, Length: 4000, dtype: object

In [163]:
df["name"].str.contains("Batman",na=False)

0       False
1       False
2       False
3       False
4       False
        ...
3995    False
3996    False
3997    False
3998    False
3999    False
Name: name, Length: 4000, dtype: bool

In [166]:
df["score_category"] = pd.cut(df["score"],bins=[0,5,7,10],labels=["low","medium","high"])
df["score_category"]

0         high
1       medium
2         high
3         high
4         high
         ...
3995    medium
3996    medium
3997    medium
3998    medium
3999       low
Name: score_category, Length: 4000, dtype: category
Categories (3, object): ['low' < 'medium' < 'high']

In [170]:
x = df[["budget","gross","votes","runtime"]]
y = df["profit"]

In [171]:
x = df[["budget","votes","runtime"]]
y = df["score"]

In [177]:
x = pd.get_dummies(df[["budget","votes","genre"]],columns=["genre"])
y = df["score"]

In [183]:
df[df["genre"]== "Action"].sort_values("score",ascending = False).head(5)

,name,rating,genre,year,released,score,votes,director,writer,star,...,runtime_movies,movie_type,score_plus_one,genre_code,name_upper,name_lower,names_len,name_clean,name_no_colon,score_final
3845,The Lord of the Rings: The Fellowship of the Ring,PG-13,Action,2001,"December 19, 2001 (United States)",8.8,1700000.0,Peter Jackson,J.R.R. Tolkien,Elijah Wood,...,long,long,9.8,A,THE LORD OF THE RINGS: THE FELLOWSHIP OF THE RING,the lord of the rings: the fellowship of the ring,49,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings The Fellowship of the Ring,8.8
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,...,medium,long,9.7,A,STAR WARS: EPISODE V - THE EMPIRE STRIKES BACK,star wars: episode v - the empire strikes back,46,Star Wars: Episode V - The Empire Strikes Back,Star Wars Episode V - The Empire Strikes Back,8.7
3443,The Matrix,R,Action,1999,"March 31, 1999 (United States)",8.7,1700000.0,Lana Wachowski,Lilly Wachowski,Keanu Reeves,...,medium,long,9.7,A,THE MATRIX,the matrix,10,The Matrix,The Matrix,8.7
3645,Gladiator,R,Action,2000,"May 5, 2000 (United States)",8.5,1400000.0,Ridley Scott,David Franzoni,Russell Crowe,...,long,long,9.5,A,GLADIATOR,gladiator,9,Gladiator,Gladiator,8.5
1843,Terminator 2: Judgment Day,R,Action,1991,"July 3, 1991 (United States)",8.5,1000000.0,James Cameron,James Cameron,Arnold Schwarzenegger,...,medium,long,9.5,A,TERMINATOR 2: JUDGMENT DAY,terminator 2: judgment day,26,Terminator 2: Judgment Day,Terminator 2 Judgment Day,8.5

In [191]:
df.sort_values("genre",ascending = False).groupby("genre").head(3)

,name,rating,genre,year,released,score,votes,director,writer,star,...,runtime_movies,movie_type,score_plus_one,genre_code,name_upper,name_lower,names_len,name_clean,name_no_colon,score_final
2382,Posse,R,Western,1993,"May 14, 1993 (United States)",5.5,4200.0,Mario Van Peebles,Sy Richardson,Mario Van Peebles,...,medium,medium,6.5,NaN,POSSE,posse,5,Posse,Posse,5.5
287,Barbarosa,PG,Western,1982,"February 19, 1982 (United States)",6.4,1500.0,Fred Schepisi,William D. Wittliff,Willie Nelson,...,medium,medium,7.4,NaN,BARBAROSA,barbarosa,9,Barbarosa,Barbarosa,6.4
202,Comin' at Ya!,R,Western,1981,"July 24, 1981 (United States)",5.1,499.0,Ferdinando Baldi,Wolfe Lowenthal,Tony Anthony,...,medium,medium,6.1,NaN,COMIN' AT YA!,comin' at ya!,13,Comin' at Ya!,Comin' at Ya!,5.1
1173,The House on Carroll Street,PG,Thriller,1987,1987 (United States),6.1,2300.0,Peter Yates,Walter Bernstein,Kelly McGillis,...,medium,medium,7.1,NaN,THE HOUSE ON CARROLL STREET,the house on carroll street,27,The House on Carroll Street,The House on Carroll Street,6.1
1149,The Fourth Protocol,R,Thriller,1987,"August 28, 1987 (United States)",6.6,9200.0,John Mackenzie,George Axelrod,Michael Caine,...,medium,medium,7.6,NaN,THE FOURTH PROTOCOL,the fourth protocol,19,The Fourth Protocol,The Fourth Protocol,6.6
470,Cross Country,R,Thriller,1983,"November 18, 1983 (United States)",5.4,182.0,Paul Lynch,Herbert Kastle,Richard Beymer,...,medium,medium,6.4,NaN,CROSS COUNTRY,cross country,13,Cross Country,Cross Country,5.4
323,Kamikaze 89,Not Rated,Sci-Fi,1982,"July 16, 1982 (West Germany)",5.8,665.0,Wolf Gremm,Robert Katz,Rainer Werner Fassbinder,...,medium,medium,6.8,NaN,KAMIKAZE 89,kamikaze 89,11,Kamikaze 89,Kamikaze 89,5.8
942,The Manhattan Project,PG-13,Sci-Fi,1986,"June 13, 1986 (United States)",6.2,5600.0,Marshall Brickman,Marshall Brickman,John Lithgow,...,medium,medium,7.2,NaN,THE MANHATTAN PROJECT,the manhattan project,21,The Manhattan Project,The Manhattan Project,6.2
1726,Hardware,R,Sci-Fi,1990,"September 14, 1990 (United States)",6.0,13000.0,Richard Stanley,Steve MacManus,Dylan McDermott,...,medium,medium,7.0,NaN,HARDWARE,hardware,8,Hardware,Hardware,6.0
521,Starman,PG,Romance,1984,"December 14, 1984 (United States)",7.0,44000.0,John Carpenter,Bruce A. Evans,Jeff Bridges,...,medium,medium,8.0,NaN,STARMAN,starman,7,Starman,Starman,7.0
3332,L'ennui,NaN,Romance,1998,"December 16, 1998 (France)",6.1,2000.0,Cédric Kahn,Cédric Kahn,Charles Berling,...,medium,long,7.1,NaN,L'ENNUI,l'ennui,7,L'ennui,L'ennui,6.1
3820,The House of Mirth,PG,Romance,2000,"October 13, 2000 (United Kingdom)",7.0,7200.0,Terence Davies,Edith Wharton,Gillian Anderson,...,medium,long,8.0,NaN,THE HOUSE OF MIRTH,the house of mirth,18,The House of Mirth,The House of Mirth,7.0
2042,Defenseless,R,Mystery,1991,"August 23, 1991 (United States)",5.6,815.0,Martin Campbell,James Cresson,Barbara Hershey,...,medium,medium,6.6,NaN,DEFENSELESS,defenseless,11,Defenseless,Defenseless,5.6
3088,Lost Highway,R,Mystery,1997,"January 15, 1997 (France)",7.6,134000.0,David Lynch,David Lynch,Bill Pullman,...,medium,long,8.6,NaN,LOST HIGHWAY,lost highway,12,Lost Highway,Lost Highway,7.6
2230,Ruby Cairo,PG-13,Mystery,1992,"October 29, 1993 (United States)",5.0,2100.0,Graeme Clifford,Robert Dillon,Andie MacDowell,...,medium,medium,6.0,NaN,RUBY CAIRO,ruby cairo,10,Ruby Cairo,Ruby Cairo,5.0
162,Diva,R,Music,1981,"April 23, 1982 (United States)",7.2,12000.0,Jean-Jacques Beineix,Daniel Odier,Wilhelmenia Fernandez,...,medium,medium,8.2,NaN,DIVA,diva,4,Diva,Diva,7.2
272,Parasite,R,Horror,1982,"March 12, 1982 (United States)",3.9,2300.0,Charles Band,Alan J. Adler,Robert Glaudini,...,short,short,4.9,H,PARASITE,parasite,8,Parasite,Parasite,3.9
1089,Prince of Darkness,R,Horror,1987,"October 23, 1987 (United States)",6.7,39000.0,John Carpenter,John Carpenter,Donald Pleasence,...,medium,medium,7.7,H,PRINCE OF DARKNESS,prince of darkness,18,Prince of Darkness,Prince of Darkness,6.7
3459,The Blair Witch Project,R,Horror,1999,"July 30, 1999 (United States)",6.5,239000.0,Daniel Myrick,Daniel Myrick,Heather Donahue,...,short,short,7.5,H,THE BLAIR WITCH PROJECT,the blair witch project,23,The Blair Witch Project,The Blair Witch Project,6.5
474,The Business of Show Business,NaN,History,1983,"February 15, 1983 (Canada)",8.3,79.0,Tom Logan,Tom Logan,NaN,...,short,short,9.3,NaN,THE BUSINESS OF SHOW BUSINESS,the business of show business,29,The Business of Show Business,The Business of Show Business,8.3
230,Cat People,R,Fantasy,1982,"April 2, 1982 (United States)",6.2,20000.0,Paul Schrader,DeWitt Bodeen,Nastassja Kinski,...,medium,medium,7.2,NaN,CAT PEOPLE,cat people,10,Cat People,Cat People,6.2
1461,Pet Sematary,R,Fantasy,1989,"April 21, 1989 (United States)",6.6,97000.0,Mary Lambert,Stephen King,Dale Midkiff,...,medium,medium,7.6,NaN,PET SEMATARY,pet sematary,12,Pet Sematary,Pet Sematary,6.6
1107,The Gate,PG-13,Fantasy,1987,"May 15, 1987 (United States)",6.1,16000.0,Tibor Takács,Michael Nankin,Stephen Dorff,...,short,short,7.1,NaN,THE GATE,the gate,8,The Gate,The Gate,6.1
2597,Lassie,PG,Family,1994,"July 22, 1994 (United States)",5.9,5400.0,Daniel Petrie,Eric Knight,Helen Slater,...,medium,medium,6.9,NaN,LASSIE,lassie,6,Lassie,Lassie,5.9
723,D.A.R.Y.L.,PG,Family,1985,"June 14, 1985 (United States)",6.3,12000.0,Simon Wincer,David Ambrose,Mary Beth Hurt,...,medium,medium,7.3,NaN,D.A.R.Y.L.,d.a.r.y.l.,10,D.A.R.Y.L.,D.A.R.Y.L.,6.3
798,One Magic Christmas,G,Family,1985,"November 22, 1985 (United States)",6.5,3400.0,Phillip Borsos,Thomas Meehan,Mary Steenburgen,...,short,short,7.5,NaN,ONE MAGIC CHRISTMAS,one magic christmas,19,One Magic Christmas,One Magic Christmas,6.5
2842,Panther,R,Drama,1995,"May 3, 1995 (United States)",6.4,2300.0,Mario Van Peebles,Melvin Van Peebles,Kadeem Hardison,...,medium,long,7.4,D,PANTHER,panther,7,Panther,Panther,6.4
802,Fever Pitch,R,Drama,1985,"November 22, 1985 (United States)",4.1,243.0,Richard Brooks,Richard Brooks,Ryan O'Neal,...,medium,medium,5.1,D,FEVER PITCH,fever pitch,11,Fever Pitch,Fever Pitch,4.1
2833,La fille seule,TV-MA,Drama,1995,"October 30, 1996 (United States)",6.9,1500.0,Benoît Jacquot,Jérôme Beaujour,Virginie Ledoyen,...,medium,medium,7.9,D,LA FILLE SEULE,la fille seule,14,La fille seule,La fille seule,6.9
1404,Stormy Monday,R,Crime,1988,May 1988 (United States),6.2,3800.0,Mike Figgis,Mike Figgis,Melanie Griffith,...,medium,medium,7.2,NaN,STORMY MONDAY,stormy monday,13,Stormy Monday,Stormy Monday,6.2
1401,Sunset,R,Crime,1988,"April 29, 1988 (United States)",5.7,3900.0,Blake Edwards,Rod Amateau,Bruce Willis,...,medium,medium,6.7,NaN,SUNSET,sunset,6,Sunset,Sunset,5.7
2067,Glengarry Glen Ross,R,Crime,1992,"October 2, 1992 (United States)",7.7,98000.0,James Foley,David Mamet,Al Pacino,...,medium,medium,8.7,NaN,GLENGARRY GLEN ROSS,glengarry glen ross,19,Glengarry Glen Ross,Glengarry Glen Ross,7.7
2216,Night and the City,R,Comedy,1992,"October 23, 1992 (United States)",5.8,4600.0,Irwin Winkler,Gerald Kersh,Robert De Niro,...,medium,medium,6.8,C,NIGHT AND THE CITY,night and the city,18,Night and the City,Night and the City,5.8
2249,Naked,Not Rated,Comedy,1993,"February 4, 1994 (United States)",7.8,36000.0,Mike Leigh,Mike Leigh,David Thewlis,...,medium,long,8.8,C,NAKED,naked,5,Naked,Naked,7.8
3128,Soul Food,R,Comedy,1997,"September 26, 1997 (United States)",7.0,7400.0,George Tillman Jr.,George Tillman Jr.,Vanessa Williams,...,medium,medium,8.0,C,SOUL FOOD,soul food,9,Soul Food,Soul Food,7.0
633,The Bear,PG,Biography,1984,"September 28, 1984 (United States)",6.1,270.0,Richard C. Sarafian,Michael Kane,Gary Busey,...,medium,medium,7.1,NaN,THE BEAR,the bear,8,The Bear,The Bear,6.1
7,Raging Bull,R,Biography,1980,"December 19, 1980 (United States)",8.2,330000.0,Martin Scorsese,Jake LaMotta,Robert De Niro,...,medium,long,9.2,NaN,RAGING BULL,raging bull,11,Raging Bull,Raging Bull,8.2
1175,Prick Up Your Ears,R,Biography,1987,"May 8, 1987 (United States)",7.3,5700.0,Stephen Frears,John Lahr,Gary Oldman,...,medium,medium,8.3,NaN,PRICK UP YOUR EARS,prick up your ears,18,Prick Up Your Ears,Prick Up Your Ears,7.3
324,The Wizard of Oz,Not Rated,Animation,1982,"October 6, 1982 (United States)",6.8,352.0,Fumihiko Takayama,Yoshimitsu Banno,Aileen Quinn,...,short,short,7.8,NaN,THE WIZARD OF OZ,the wizard of oz,16,The Wizard of Oz,The Wizard of Oz,6.8
2509,The Pagemaster,G,Animation,1994,"November 23, 1994 (United States)",6.1,22000.0,Pixote Hunt,David Kirschner,Macaulay Culkin,...,short,short,7.1,NaN,THE PAGEMASTER,the pagemaster,14,The Pagemaster,The Pagemaster,6.1
3592,Pokémon the Movie 2000,G,Animation,1999,"July 21, 2000 (United States)",6.1,21000.0,Michael Haigney,Satoshi Tajiri,Veronica Taylor,...,medium,medium,7.1,NaN,POKÉMON THE MOVIE 2000,pokémon the movie 2000,22,Pokémon the Movie 2000,Pokémon the Movie 2000,6.1
2760,Senior Trip,R,Adventure,1995,"September 8, 1995 (United States)",5.7,5500.0,Kelly Makin,Roger Kumble,Matt Frewer,...,medium,medium,6.7,NaN,SENIOR TRIP,senior trip,11,Senior Trip,Senior Trip,5.7
2761,Free Willy 2: The Adventure Home,PG,Adventure,1995,"July 19, 1995 (United States)",5.1,17000.0,Dwight H. Little,Keith Walker,Jason James Richter,...,medium,medium,6.1,NaN,FREE WILLY 2: THE ADVENTURE HOME,free willy 2: the adventure home,32,Free Willy 2: The Adventure Home,Free Willy 2 The Adventure Home,5.1
402,High Road to China,PG,Adventure,1983,"March 18, 1983 (United States)",6.1,5100.0,Brian G. Hutton,Jon Cleary,Tom Selleck,...,medium,medium,7.1,NaN,HIGH ROAD TO CHINA,high road to china,18,High Road to China,High Road to China,6.1
466,Deadly Force,R,Action,1983,"July 15, 1983 (United States)",4.9,300.0,Paul Aaron,Ken Barnett,Wings Hauser,...,medium,medium,5.9,A,DEADLY FORCE,deadly force,12,Deadly Force,Deadly Force,4.9
516,Star Trek III: The Search for Spock,PG,Action,1984,"June 1, 1984 (United States)",6.7,76000.0,Leonard Nimoy,Gene Roddenberry,William Shatner,...,medium,medium,7.7,A,STAR TREK III: THE SEARCH FOR SPOCK,star trek iii: the search for spock,35,Star Trek III: The Search for Spock,Star Trek III The Search for Spock,6.7
475,The Terminator,R,Action,1984,"October 26, 1984 (United States)",8.0,812000.0,James Cameron,James Cameron,Arnold Schwarzenegger,...,medium,medium,9.0,A,THE TERMINATOR,the terminator,14,The Terminator,The Terminator,8.0

In [195]:
df.groupby("genre", as_index=False)["score"].mean().sort_values("score", ascending=False)

        genre     score
9     History  8.300000
11      Music  7.200000
3   Biography  7.052000
2   Animation  6.883186
6       Drama  6.673606
5       Crime  6.645033
7      Family  6.550000
12    Mystery  6.500000
13    Romance  6.400000
4      Comedy  6.179410
1   Adventure  6.151948
8     Fantasy  6.024242
0      Action  6.014968
14     Sci-Fi  5.983333
15   Thriller  5.890909
10     Horror  5.744304
16    Western  5.666667

In [196]:
df.groupby("genre",as_index=False)["score"].mean().sort_values("score",ascending=False)

        genre     score
9     History  8.300000
11      Music  7.200000
3   Biography  7.052000
2   Animation  6.883186
6       Drama  6.673606
5       Crime  6.645033
7      Family  6.550000
12    Mystery  6.500000
13    Romance  6.400000
4      Comedy  6.179410
1   Adventure  6.151948
8     Fantasy  6.024242
0      Action  6.014968
14     Sci-Fi  5.983333
15   Thriller  5.890909
10     Horror  5.744304
16    Western  5.666667

In [200]:
df.groupby("genre",as_index = False)["votes"].sum().sort_values("votes",ascending = False).head(5)

       genre       votes
0     Action  60294155.0
4     Comedy  46704518.0
6      Drama  41455729.0
5      Crime  22012705.0
1  Adventure  13539506.0

In [204]:
filtered = df.groupby("genre",as_index = False).filter(lambda x: len(x)>100)
filtered.groupby("genre",as_index = False)["score"].mean().sort_values("score",ascending=False)

       genre     score
3  Biography  7.052000
2  Animation  6.883186
6      Drama  6.673606
5      Crime  6.645033
4     Comedy  6.179410
1  Adventure  6.151948
0     Action  6.014968
7     Horror  5.744304

In [205]:
df.loc[(df["budget"].isna()) & (df["gross"].notna()),["name","budget","gross"]]

Empty DataFrame
Columns: [name, budget, gross]
Index: []

In [206]:
df["rating"].fillna("not_rated")

0        R
1        R
2       PG
3       PG
4        R
        ..
3995     R
3996     R
3997     R
3998     R
3999    PG
Name: rating, Length: 4000, dtype: object

In [220]:
df.sort_values("gross",ascending=False).head(10) [["name","gross","budget"]]

,name,gross,budget
3045,Titanic,2.201647e+09,200000000
2448,The Lion King,1.083721e+09,45000000
2245,Jurassic Park,1.033928e+09,63000000
3451,Star Wars: Episode I - The Phantom Menace,1.027083e+09,115000000
3843,Harry Potter and the Sorcerer's Stone,1.006968e+09,125000000
3845,The Lord of the Rings: The Fellowship of the Ring,8.976901e+08,93000000
2844,Independence Day,8.174009e+08,75000000
209,E.T. the Extra-Terrestrial,7.929106e+08,10500000
2445,Forrest Gump,6.782261e+08,55000000
3453,The Sixth Sense,6.728063e+08,40000000

In [228]:
df[(df["score"]>7.5) & (df["runtime"]<120)][["name","score","runtime"]]

                                               name  score  runtime
3                                         Airplane!    7.7     88.0
41                                   Breaker Morant    7.9    107.0
83                     The King and the Mockingbird    7.9     83.0
92    Indiana Jones and the Raiders of the Lost Ark    8.4    115.0
101                                       Mad Max 2    7.6     96.0
...                                             ...    ...      ...
3934                      Hedwig and the Angry Inch    7.7     95.0
3950                                    Waking Life    7.8     99.0
3958                        Cowboy Bebop: The Movie    7.9    115.0
3980                             Millennium Actress    7.9     87.0
3988                                  No Man's Land    7.9     98.0

[203 rows x 3 columns]